steps:
  - id: "rodando testes unitários"
    name: "golang"
    args: ["go", "test", "./golang-hpa", "-v"]

  - id: "gerando o executavel"
    name: "golang"
    args: ["go", "build", "-o", "cpu-stresser", "./golang-hpa"]

  - id: "build na imagem"
    name: "docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA", "-f", "./golang-hpa/Dockerfile", "."]

  - id: "ajustando arquivo de deployment"
    name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment.prod.yaml;
        cat k8s/deployment.prod.yaml;

  - id: "deployment k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args: 
      - "apply"
      - "-f" 
      - "k8s/deployment.prod.yaml"
      - "-f"
      - "k8s/service.yaml"
      - "-f"
      - "k8s/hpa.yaml"
    env:
    - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
    - "CLOUDSDK_CONTAINER_CLUSTER=cluster-go-hpa"

images:
  - 'gcr.io/$PROJECT_ID/go-hpa'